"Date" :"String",
"OrderId":"String",
"MbeId": "String",
"Isin":"String",
"IssuerName":"String",
"CouponRate":"String",
"MaturityDate":"String",
"Ltp":"String",
"FaceValue":"String",
"CreditRating":"String",
"NumOfToken":"String",
"NumOfLots":"String",
"TransactionsType":"String",
"DetokenizedToken":"String",
"AskedPrice":"String",
"BidPrice":"String",
"PurhcasePrice":"String",
"CurrentPrice":"String",
"Amount":"String",
"Authorization":"String",
"Status":"String",  