const bond = [
  {
    Isin: "INE00XE07101",
    MbeId: "muhsin@inclusivegrowthchain.com",
    IssuerName: "MUTHOOT VEHICLE & ASSET FINANCE LIMITED",
    CouponRate: "9.50%",
    FaceValue: 1,
    Ltp: 1.015,
    CreditRating: "CRISIL A/Stable;CARE BBB+",
    MaturityDate: "17-05-2023",
    SecurityDescription:
      "MUTHOOT VEHICLE & ASSET FINANCE LIMITED OPTION II 9.50 NCD 17MY23 FVRS1000",
    Currency: "Rupee",
    noOfLots: 2,
    TokenizedLot: 1,
    TotalTokenQty: 200000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    IsTokenized: false,
    IsProcessed: true,
  },
  {
    Isin: "INE01I507042",
    MbeId: "shreyanshnema@inclusivegrowthchain.com",
    IssuerName: "KLM AXIVA FINVEST LIMITED",
    CouponRate: "12.00%",
    FaceValue: 1,
    Ltp: 0.98,
    CreditRating: "CARE BB+/Stable",
    MaturityDate: "05-11-2023",
    SecurityDescription:
      "KLM AXIVA FINVEST LIMITED OPT IV 12 LOA 05NV23 FVRS1000",
    Currency: "Rupee",
    noOfLots: 1,
    TokenizedLot: 0,
    TotalTokenQty: 0,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    IsTokenized: false,
    IsProcessed: true,
  },
  {
    Isin: "INE027E07923",
    MbeId: "rajkumar@inclusivegrowthchain.com",
    IssuerName: "L&T FINANCE LIMITED",
    CouponRate: "9.10%",
    FaceValue: 1,
    Ltp: 1.12,
    CreditRating: "IND AAA/Stable;ICRA AAA/Stable;CARE AAA/Stable",
    MaturityDate: "08-09-2032",
    SecurityDescription:
      "L&T FINANCE LIMITED SR III OPT 1 9.1 LOA 13MR24 FVRS1000",
    Currency: "Rupee",
    noOfLots: 4,
    TokenizedLot: 2,
    TotalTokenQty: 400000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    IsTokenized: false,
    IsProcessed: true,
  },
  {
    Isin: "INE033L07FZ3",
    MbeId: "prudhvi@inclusivegrowthchain.com",
    IssuerName: "TATA CAPITAL HOUSING FINANCE LIMITED",
    CouponRate: "8.80%",
    FaceValue: 1,
    Ltp: 0.89,
    CreditRating: "CRISIL AAA/Stable",
    MaturityDate: "25-09-2023",
    SecurityDescription:
      "TATA CAPITAL HOUSING FINANCE LIMITED 8.8 NCD 25SP23 FVRS1000",
    Currency: "Rupee",
    noOfLots: 3,
    TokenizedLot: 2,
    TotalTokenQty: 400000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    IsTokenized: false,
    IsProcessed: true,
  },
  {
    Isin: "INE101Q07391",
    MbeId: "rishav.goenka@inclusivegrowthchain.com",
    IssuerName: "MUTHOOTTU MINI FINANCIERS LTD",
    CouponRate: "10.00%",
    FaceValue: 1,
    Ltp: 0.99,
    CreditRating: "IND A-/Stable",
    MaturityDate: "24-04-2024",
    SecurityDescription:
      "MUTHOOTTU MINI FINANCIERS LTD SERIES VIII-V 10 NCD 24AP24 FVRS1000",
    Currency: "Rupee",
    noOfLots: 5,
    TokenizedLot: 3,
    TotalTokenQty: 600000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    IsTokenized: false,
    IsProcessed: true,
  },
  {
    Isin: "INE039A07801",
    MbeId: "muhsin@inclusivegrowthchain.com",
    IssuerName: "IFCI LIMITED",
    CouponRate: "9.90%",
    FaceValue: 1,
    Ltp: 1.14,
    CreditRating: "ICRA B+/Negative;BWR BB/Negative",
    MaturityDate: "01-12-2024",
    SecurityDescription:
      "IFCI LIMITED SR-VI 9.9 NCD 01DC24 FVRS1000 LOA UPTO 17MY15",
    Currency: "Rupee",
    noOfLots: 2,
    TokenizedLot: 1,
    TotalTokenQty: 200000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    IsTokenized: false,
    IsProcessed: true,
  },
  {
    Isin: "INE217K07AF7",
    MbeId: "shreyanshnema@inclusivegrowthchain.com",
    IssuerName: "RELIANCE HOME FINANCE LIMITED",
    CouponRate: "9.00%",
    FaceValue: 1,
    Ltp: 0.98,
    CreditRating: "CRISIL AAA / Stable",
    MaturityDate: "04-11-2025",
    SecurityDescription:
      "RELIANCE HOME FINANCE LIMITED SR-III CAT I & II 9 NCD 03JN27 FVRS1000",
    Currency: "Rupee",
    noOfLots: 4,
    TokenizedLot: 2,
    TotalTokenQty: 400000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    IsTokenized: false,
    IsProcessed: true,
  },
  {
    Isin: "INE219X07173",
    MbeId: "rajkumar@inclusivegrowthchain.com",
    IssuerName: "INDIA GRID TRUST",
    CouponRate: "6.65%",
    FaceValue: 1,
    Ltp: 1.25,
    CreditRating: "IND AAA/Stable ;CRISIL AAA/Stable",
    MaturityDate: "06-05-2024",
    SecurityDescription:
      "INDIA GRID TRUST SR I CAT I&II 6.65 NCD 06MY24 FVRS1000",
    Currency: "Rupee",
    noOfLots: 3,
    TokenizedLot: 1,
    TotalTokenQty: 200000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    IsTokenized: false,
    IsProcessed: true,
  },
  {
    Isin: "INE342T07189",
    MbeId: "prudhvi@inclusivegrowthchain.com",
    IssuerName: "NAVI FINSERV LIMITED",
    CouponRate: "9.20%",
    FaceValue: 1,
    Ltp: 0.79,
    CreditRating: "IND A/Stable",
    MaturityDate: "28-03-2024",
    SecurityDescription: "NAVI FINSERV LIMITED SR I 9.20 NCD 08DC23 FVRS1000",
    Currency: "Rupee",
    noOfLots: 1,
    TokenizedLot: 1,
    TotalTokenQty: 200000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    IsTokenized: false,
    IsProcessed: true,
  },
  {
    Isin: "INE774D07ST5",
    MbeId: "rishav.goenka@inclusivegrowthchain.com",
    IssuerName: "MAHINDRA & MAHINDRA FINANCIAL SERVICES LTD",
    CouponRate: "9.10%",
    FaceValue: 1,
    Ltp: 1.311,
    CreditRating: "IND AAA/Stable ;CARE AAA/Stable",
    MaturityDate: "18-01-2024",
    SecurityDescription:
      "MAHINDRA & MAHINDRA FINANCIAL SERVICES LTD SRIICATI&II9.10NCD 18JN24FV1000 LOAUPTO21JN19",
    Currency: "Rupee",
    noOfLots: 5,
    TokenizedLot: 4,
    TotalTokenQty: 800000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    IsTokenized: false,
    IsProcessed: true,
  },
  {
    Isin: "INE804I075Y4",
    MbeId: "muhsin@inclusivegrowthchain.com",
    IssuerName: "ECL FINANCE LIMITED",
    CouponRate: "9.25%",
    FaceValue: 1,
    Ltp: 0.87,
    CreditRating: "CRISIL AA-/Negative;ICRA A+/Stable ()",
    MaturityDate: "06-08-2023",
    SecurityDescription: "ECL FINANCE LIMITED SR-III 9.25 NCD 06AG23 FVRS1000",
    Currency: "Rupee",
    noOfLots: 1,
    TokenizedLot: 0,
    TotalTokenQty: 0,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    IsTokenized: false,
    IsProcessed: true,
  },
  {
    Isin: "INE872A07UQ5",
    MbeId: "shreyanshnema@inclusivegrowthchain.com",
    IssuerName: "SREI EQUIPMENT FINANCE LIMITED",
    CouponRate: "8.65%",
    FaceValue: 1,
    Ltp: 1.31,
    CreditRating: "BWR D",
    MaturityDate: "16-03-2023",
    SecurityDescription:
      "SREI EQUIPMENT FINANCE LTD SR-VI 8.65 LOA 16MR23 FVRS1000",
    Currency: "Rupee",
    noOfLots: 4,
    TokenizedLot: 2,
    TotalTokenQty: 400000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    IsTokenized: false,
    IsProcessed: true,
  },
  {
    Isin: "INE918K07FP8",
    MbeId: "rajkumar@inclusivegrowthchain.com",
    IssuerName: "NUVAMA WEALTH FINANCE LIMITED",
    CouponRate: "10%",
    FaceValue: 1,
    Ltp: 1.05,
    CreditRating: "CRISIL AA-/Stable;CARE AA-/Stable ()",
    MaturityDate: "05-02-2023",
    SecurityDescription:
      "NUVAMA WEALTH FINANCE LIMITED SR III 10 NCD 05FB23 FVRS1000",
    Currency: "Rupee",
    noOfLots: 3,
    TokenizedLot: 1,
    TotalTokenQty: 200000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    IsTokenized: false,
    IsProcessed: true,
  },
  {
    Isin: "INE945W07399",
    MbeId: "prudhvi@inclusivegrowthchain.com",
    IssuerName: "INCRED FINANCIAL SERVICES LIMITED",
    CouponRate: "9.25%",
    FaceValue: 1,
    Ltp: 0.971,
    CreditRating: "CRISIL A+/Stable ()",
    MaturityDate: "18-02-2024",
    SecurityDescription:
      "INCRED FINANCIAL SERVICES LIMITED SR 2 9.25 NCD 18FB24 FVRS1000",
    Currency: "Rupee",
    noOfLots: 2,
    TokenizedLot: 1,
    TotalTokenQty: 200000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    IsTokenized: false,
    IsProcessed: true,
  },
  {
    Isin: "INE884Q07061",
    MbeId: "rishav.goenka@inclusivegrowthchain.com",
    IssuerName: "MIDLAND MICROFIN LIMITED",
    CouponRate: "12%",
    FaceValue: 1,
    Ltp: 0.89,
    CreditRating: "CARE BBB/Positive ()",
    MaturityDate: "04-01-2024",
    SecurityDescription:
      "MIDLAND MICROFIN LIMITED OPT 6 12 NCD 04JN24 FVRS10000",
    Currency: "Rupee",
    noOfLots: 4,
    TokenizedLot: 2,
    TotalTokenQty: 400000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    IsTokenized: false,
    IsProcessed: true,
  },
  {
    Isin: "INE866I08279",
    MbeId: "muhsin@inclusivegrowthchain.com",
    IssuerName: "IIFL FINANCE LIMITED",
    CouponRate: "10%",
    FaceValue: 1,
    Ltp: 1.16,
    CreditRating: "CRISIL AA/Stable;ICRA AA/Stable;BWR AA+/Stable",
    MaturityDate: "07-02-2029",
    SecurityDescription: "IIFL FINANCE LIMITED SR V 10 NCD 07FB29 FVRS1000",
    Currency: "Rupee",
    noOfLots: 6,
    TokenizedLot: 3,
    TotalTokenQty: 600000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    IsTokenized: false,
    IsProcessed: true,
  },
  {
    Isin: "INE774D08LT8",
    MbeId: "shreyanshnema@inclusivegrowthchain.com",
    IssuerName: "MAHINDRA & MAHINDRA FINANCIAL SERVICES LTD",
    CouponRate: "8.53%",
    FaceValue: 1,
    Ltp: 1,
    CreditRating: "IND AAA/Stable ();CARE AAA/Stable ()",
    MaturityDate: "06-06-2026",
    SecurityDescription:
      "MAHINDRA & MAHINDRA FINANCIAL SERVICES LTD SR-III8.53 NCD06JU26FVRS1000LOAUPTO24JL16",
    Currency: "Rupee",
    noOfLots: 10,
    TokenizedLot: 6,
    TotalTokenQty: 1200000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    IsTokenized: false,
    IsProcessed: true,
  },
  {
    Isin: "INE721A07PE0",
    MbeId: "rajkumar@inclusivegrowthchain.com",
    IssuerName: "SHRIRAM FINANCE LIMITED",
    CouponRate: "9.70%",
    FaceValue: 1,
    Ltp: 1.11,
    CreditRating: "CARE AA+/Stable ();IND AA+/Stable ();CRISIL AA+/Stable",
    MaturityDate: "22-08-2026",
    SecurityDescription:
      "SHRIRAM FINANCE LIMITED SERIES VII NCD 9.70 22AG26 FVRS1000",
    Currency: "Rupee",
    noOfLots: 2,
    TokenizedLot: 1,
    TotalTokenQty: 200000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    IsTokenized: false,
    IsProcessed: true,
  },
  {
    Isin: "INE651J07606",
    MbeId: "prudhvi@inclusivegrowthchain.com",
    IssuerName: "JM FINANCIAL CREDIT SOLUTIONS LIMITED",
    CouponRate: "9.50%",
    FaceValue: 1,
    Ltp: 0.88,
    CreditRating: "IND AA/Stable ();ICRA AA/Stable",
    MaturityDate: "07-06-2023",
    SecurityDescription:
      "JM FINANCIAL CREDIT SOLUTIONS LIMITED TR 1 OPT III 9.5 NCD 07JU23 FVRS1000",
    Currency: "Rupee",
    noOfLots: 3,
    TokenizedLot: 3,
    TotalTokenQty: 600000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    IsTokenized: false,
    IsProcessed: true,
  },
  {
    Isin: "INE583D07240",
    MbeId: "rishav.goenka@inclusivegrowthchain.com",
    IssuerName: "UGRO CAPITAL LIMITED",
    CouponRate: "10%",
    FaceValue: 1,
    Ltp: 1,
    CreditRating: "ACUITE A/Stable ()",
    MaturityDate: "04-11-2023",
    SecurityDescription: "UGRO CAPITAL LIMITED SR I 10 NCD 04NV23 FVRS1000",
    Currency: "Rupee",
    noOfLots: 4,
    TokenizedLot: 2,
    TotalTokenQty: 400000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    IsTokenized: false,
    IsProcessed: true,
  },
  {
    Isin: "INE01I507042",
    MbeId: "prudhvi@inclusivegrowthchain.com",
    IssuerName: "KLM AXIVA FINVEST LIMITED",
    CouponRate: "12.00%",
    FaceValue: 1,
    Ltp: 0.98,
    CreditRating: "CARE BB+/Stable",
    MaturityDate: "05-11-2023",
    SecurityDescription:
      "KLM AXIVA FINVEST LIMITED OPT IV 12 LOA 05NV23 FVRS1000",
    Currency: "Rupee",
    noOfLots: 1,
    TokenizedLot: 0,
    TotalTokenQty: 0,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    IsTokenized: false,
    IsProcessed: true,
  },
  {
    Isin: "INE033L07FZ3",
    MbeId: "shreyanshnema@inclusivegrowthchain.com",
    IssuerName: "TATA CAPITAL HOUSING FINANCE LIMITED",
    CouponRate: "8.80%",
    FaceValue: 1,
    Ltp: 0.89,
    CreditRating: "CRISIL AAA/Stable",
    MaturityDate: "25-09-2023",
    SecurityDescription:
      "TATA CAPITAL HOUSING FINANCE LIMITED 8.8 NCD 25SP23 FVRS1000",
    Currency: "Rupee",
    noOfLots: 3,
    TokenizedLot: 2,
    TotalTokenQty: 400000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    IsTokenized: false,
    IsProcessed: true,
  },
  {
    Isin: "INE039A07801",
    MbeId: "rishav.goenka@inclusivegrowthchain.com",
    IssuerName: "IFCI LIMITED",
    CouponRate: "9.90%",
    FaceValue: 1,
    Ltp: 1.14,
    CreditRating: "ICRA B+/Negative;BWR BB/Negative",
    MaturityDate: "01-12-2024",
    SecurityDescription:
      "IFCI LIMITED SR-VI 9.9 NCD 01DC24 FVRS1000 LOA UPTO 17MY15",
    Currency: "Rupee",
    noOfLots: 2,
    TokenizedLot: 1,
    TotalTokenQty: 200000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    IsTokenized: false,
    IsProcessed: true,
  },
  {
    Isin: "INE217K07AF7",
    MbeId: "prudhvi@inclusivegrowthchain.com",
    IssuerName: "RELIANCE HOME FINANCE LIMITED",
    CouponRate: "9.00%",
    FaceValue: 1,
    Ltp: 0.98,
    CreditRating: "CRISIL AAA / Stable",
    MaturityDate: "04-11-2025",
    SecurityDescription:
      "RELIANCE HOME FINANCE LIMITED SR-III CAT I & II 9 NCD 03JN27 FVRS1000",
    Currency: "Rupee",
    noOfLots: 4,
    TokenizedLot: 1,
    TotalTokenQty: 200000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    IsTokenized: false,
    IsProcessed: true,
  },
  {
    Isin: "INE342T07189",
    MbeId: "shreyanshnema@inclusivegrowthchain.com",
    IssuerName: "NAVI FINSERV LIMITED",
    CouponRate: "9.20%",
    FaceValue: 1,
    Ltp: 0.79,
    CreditRating: "IND A/Stable",
    MaturityDate: "28-03-2024",
    SecurityDescription: "NAVI FINSERV LIMITED SR I 9.20 NCD 08DC23 FVRS1000",
    Currency: "Rupee",
    noOfLots: 1,
    TokenizedLot: 0,
    TotalTokenQty: 0,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    IsTokenized: false,
    IsProcessed: true,
  },
  {
    Isin: "INE774D07ST5",
    MbeId: "muhsin@inclusivegrowthchain.com",
    IssuerName: "MAHINDRA & MAHINDRA FINANCIAL SERVICES LTD",
    CouponRate: "9.10%",
    FaceValue: 1,
    Ltp: 1.311,
    CreditRating: "IND AAA/Stable ;CARE AAA/Stable",
    MaturityDate: "18-01-2024",
    SecurityDescription:
      "MAHINDRA & MAHINDRA FINANCIAL SERVICES LTD SRIICATI&II9.10NCD 18JN24FV1000 LOAUPTO21JN19",
    Currency: "Rupee",
    noOfLots: 5,
    TokenizedLot: 3,
    TotalTokenQty: 600000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    IsTokenized: false,
    IsProcessed: true,
  },
  {
    Isin: "INE804I075Y4",
    MbeId: "rishav.goenka@inclusivegrowthchain.com",
    IssuerName: "ECL FINANCE LIMITED",
    CouponRate: "9.25%",
    FaceValue: 1,
    Ltp: 0.87,
    CreditRating: "CRISIL AA-/Negative;ICRA A+/Stable ()",
    MaturityDate: "06-08-2023",
    SecurityDescription: "ECL FINANCE LIMITED SR-III 9.25 NCD 06AG23 FVRS1000",
    Currency: "Rupee",
    noOfLots: 1,
    TokenizedLot: 1,
    TotalTokenQty: 200000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    IsTokenized: false,
    IsProcessed: true,
  },
  {
    Isin: "INE872A07UQ5",
    MbeId: "prudhvi@inclusivegrowthchain.com",
    IssuerName: "SREI EQUIPMENT FINANCE LIMITED",
    CouponRate: "8.65%",
    FaceValue: 1,
    Ltp: 1.31,
    CreditRating: "BWR D",
    MaturityDate: "16-03-2023",
    SecurityDescription:
      "SREI EQUIPMENT FINANCE LTD SR-VI 8.65 LOA 16MR23 FVRS1000",
    Currency: "Rupee",
    noOfLots: 4,
    TokenizedLot: 2,
    TotalTokenQty: 400000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    IsTokenized: false,
    IsProcessed: true,
  },
  {
    Isin: "INE945W07399",
    MbeId: "shreyanshnema@inclusivegrowthchain.com",
    IssuerName: "INCRED FINANCIAL SERVICES LIMITED",
    CouponRate: "9.25%",
    FaceValue: 1,
    Ltp: 0.971,
    CreditRating: "CRISIL A+/Stable ()",
    MaturityDate: "18-02-2024",
    SecurityDescription:
      "INCRED FINANCIAL SERVICES LIMITED SR 2 9.25 NCD 18FB24 FVRS1000",
    Currency: "Rupee",
    noOfLots: 2,
    TokenizedLot: 1,
    TotalTokenQty: 200000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    IsTokenized: false,
    IsProcessed: true,
  },
  {
    Isin: "INE884Q07061",
    MbeId: "muhsin@inclusivegrowthchain.com",
    IssuerName: "MIDLAND MICROFIN LIMITED",
    CouponRate: "12%",
    FaceValue: 1,
    Ltp: 0.89,
    CreditRating: "CARE BBB/Positive ()",
    MaturityDate: "04-01-2024",
    SecurityDescription:
      "MIDLAND MICROFIN LIMITED OPT 6 12 NCD 04JN24 FVRS10000",
    Currency: "Rupee",
    noOfLots: 4,
    TokenizedLot: 3,
    TotalTokenQty: 600000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    IsTokenized: false,
    IsProcessed: true,
  },
  {
    Isin: "INE866I08279",
    MbeId: "rishav.goenka@inclusivegrowthchain.com",
    IssuerName: "IIFL FINANCE LIMITED",
    CouponRate: "10%",
    FaceValue: 1,
    Ltp: 1.16,
    CreditRating: "CRISIL AA/Stable;ICRA AA/Stable;BWR AA+/Stable",
    MaturityDate: "07-02-2029",
    SecurityDescription: "IIFL FINANCE LIMITED SR V 10 NCD 07FB29 FVRS1000",
    Currency: "Rupee",
    noOfLots: 6,
    TokenizedLot: 3,
    TotalTokenQty: 600000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    IsTokenized: false,
    IsProcessed: true,
  },
  {
    Isin: "INE651J07606",
    MbeId: "shreyanshnema@inclusivegrowthchain.com",
    IssuerName: "JM FINANCIAL CREDIT SOLUTIONS LIMITED",
    CouponRate: "9.50%",
    FaceValue: 1,
    Ltp: 0.88,
    CreditRating: "IND AA/Stable ();ICRA AA/Stable",
    MaturityDate: "07-06-2023",
    SecurityDescription:
      "JM FINANCIAL CREDIT SOLUTIONS LIMITED TR 1 OPT III 9.5 NCD 07JU23 FVRS1000",
    Currency: "Rupee",
    noOfLots: 3,
    TokenizedLot: 3,
    TotalTokenQty: 600000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    IsTokenized: false,
    IsProcessed: true,
  },
  {
    Isin: "INE583D07240",
    MbeId: "muhsin@inclusivegrowthchain.com",
    IssuerName: "UGRO CAPITAL LIMITED",
    CouponRate: "10%",
    FaceValue: 1,
    Ltp: 1,
    CreditRating: "ACUITE A/Stable ()",
    MaturityDate: "04-11-2023",
    SecurityDescription: "UGRO CAPITAL LIMITED SR I 10 NCD 04NV23 FVRS1000",
    Currency: "Rupee",
    noOfLots: 4,
    TokenizedLot: 2,
    TotalTokenQty: 400000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    IsTokenized: false,
    IsProcessed: true,
  },
  {
    Isin: "INE01I507042",
    MbeId: "muhsin@inclusivegrowthchain.com",
    IssuerName: "KLM AXIVA FINVEST LIMITED",
    CouponRate: "12.00%",
    FaceValue: 1,
    Ltp: 0.98,
    CreditRating: "CARE BB+/Stable",
    MaturityDate: "05-11-2023",
    SecurityDescription:
      "KLM AXIVA FINVEST LIMITED OPT IV 12 LOA 05NV23 FVRS1000",
    Currency: "Rupee",
    noOfLots: 4,
    TokenizedLot: 3,
    TotalTokenQty: 600000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    IsTokenized: false,
    IsProcessed: true,
  },
  {
    Isin: "INE027E07923",
    MbeId: "rishav.goenka@inclusivegrowthchain.com",
    IssuerName: "L&T FINANCE LIMITED",
    CouponRate: "9.10%",
    FaceValue: 1,
    Ltp: 1.12,
    CreditRating: "IND AAA/Stable;ICRA AAA/Stable;CARE AAA/Stable",
    MaturityDate: "08-09-2032",
    SecurityDescription:
      "L&T FINANCE LIMITED SR III OPT 1 9.1 LOA 13MR24 FVRS1000",
    Currency: "Rupee",
    noOfLots: 6,
    TokenizedLot: 2,
    TotalTokenQty: 400000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    IsTokenized: false,
    IsProcessed: true,
  },
  {
    Isin: "INE033L07FZ3",
    MbeId: "rajkumar@inclusivegrowthchain.com",
    IssuerName: "TATA CAPITAL HOUSING FINANCE LIMITED",
    CouponRate: "8.80%",
    FaceValue: 1,
    Ltp: 0.89,
    CreditRating: "CRISIL AAA/Stable",
    MaturityDate: "25-09-2023",
    SecurityDescription:
      "TATA CAPITAL HOUSING FINANCE LIMITED 8.8 NCD 25SP23 FVRS1000",
    Currency: "Rupee",
    noOfLots: 9,
    TokenizedLot: 5,
    TotalTokenQty: 1000000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    IsTokenized: false,
    IsProcessed: true,
  },
  {
    Isin: "INE101Q07391",
    MbeId: "prudhvi@inclusivegrowthchain.com",
    IssuerName: "MUTHOOTTU MINI FINANCIERS LTD",
    CouponRate: "10.00%",
    FaceValue: 1,
    Ltp: 0.99,
    CreditRating: "IND A-/Stable",
    MaturityDate: "24-04-2024",
    SecurityDescription:
      "MUTHOOTTU MINI FINANCIERS LTD SERIES VIII-V 10 NCD 24AP24 FVRS1000",
    Currency: "Rupee",
    noOfLots: 10,
    TokenizedLot: 4,
    TotalTokenQty: 800000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    IsTokenized: false,
    IsProcessed: true,
  },
  {
    Isin: "INE217K07AF7",
    MbeId: "muhsin@inclusivegrowthchain.com",
    IssuerName: "RELIANCE HOME FINANCE LIMITED",
    CouponRate: "9.00%",
    FaceValue: 1,
    Ltp: 0.98,
    CreditRating: "CRISIL AAA / Stable",
    MaturityDate: "04-11-2025",
    SecurityDescription:
      "RELIANCE HOME FINANCE LIMITED SR-III CAT I & II 9 NCD 03JN27 FVRS1000",
    Currency: "Rupee",
    noOfLots: 6,
    TokenizedLot: 4,
    TotalTokenQty: 800000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    IsTokenized: false,
    IsProcessed: true,
  },
  {
    Isin: "INE219X07173",
    MbeId: "shreyanshnema@inclusivegrowthchain.com",
    IssuerName: "INDIA GRID TRUST",
    CouponRate: "6.65%",
    FaceValue: 1,
    Ltp: 1.25,
    CreditRating: "IND AAA/Stable ;CRISIL AAA/Stable",
    MaturityDate: "06-05-2024",
    SecurityDescription:
      "INDIA GRID TRUST SR I CAT I&II 6.65 NCD 06MY24 FVRS1000",
    Currency: "Rupee",
    noOfLots: 1,
    TokenizedLot: 1,
    TotalTokenQty: 200000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    IsTokenized: false,
    IsProcessed: true,
  },
  {
    Isin: "INE342T07189",
    MbeId: "rishav.goenka@inclusivegrowthchain.com",
    IssuerName: "NAVI FINSERV LIMITED",
    CouponRate: "9.20%",
    FaceValue: 1,
    Ltp: 0.79,
    CreditRating: "IND A/Stable",
    MaturityDate: "28-03-2024",
    SecurityDescription: "NAVI FINSERV LIMITED SR I 9.20 NCD 08DC23 FVRS1000",
    Currency: "Rupee",
    noOfLots: 4,
    TokenizedLot: 0,
    TotalTokenQty: 0,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    IsTokenized: false,
    IsProcessed: true,
  },
  {
    Isin: "INE774D07ST5",
    MbeId: "prudhvi@inclusivegrowthchain.com",
    IssuerName: "MAHINDRA & MAHINDRA FINANCIAL SERVICES LTD",
    CouponRate: "9.10%",
    FaceValue: 1,
    Ltp: 1.311,
    CreditRating: "IND AAA/Stable ;CARE AAA/Stable",
    MaturityDate: "18-01-2024",
    SecurityDescription:
      "MAHINDRA & MAHINDRA FINANCIAL SERVICES LTD SRIICATI&II9.10NCD 18JN24FV1000 LOAUPTO21JN19",
    Currency: "Rupee",
    noOfLots: 2,
    TokenizedLot: 2,
    TotalTokenQty: 400000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    IsTokenized: false,
    IsProcessed: true,
  },
  {
    Isin: "INE872A07UQ5",
    MbeId: "muhsin@inclusivegrowthchain.com",
    IssuerName: "SREI EQUIPMENT FINANCE LIMITED",
    CouponRate: "8.65%",
    FaceValue: 1,
    Ltp: 1.31,
    CreditRating: "BWR D",
    MaturityDate: "16-03-2023",
    SecurityDescription:
      "SREI EQUIPMENT FINANCE LTD SR-VI 8.65 LOA 16MR23 FVRS1000",
    Currency: "Rupee",
    noOfLots: 9,
    TokenizedLot: 6,
    TotalTokenQty: 1200000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    IsTokenized: false,
    IsProcessed: true,
  },
  {
    Isin: "INE918K07FP8",
    MbeId: "rishav.goenka@inclusivegrowthchain.com",
    IssuerName: "NUVAMA WEALTH FINANCE LIMITED",
    CouponRate: "10%",
    FaceValue: 1,
    Ltp: 1.05,
    CreditRating: "CRISIL AA-/Stable;CARE AA-/Stable ()",
    MaturityDate: "05-02-2023",
    SecurityDescription:
      "NUVAMA WEALTH FINANCE LIMITED SR III 10 NCD 05FB23 FVRS1000",
    Currency: "Rupee",
    noOfLots: 10,
    TokenizedLot: 8,
    TotalTokenQty: 1600000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    IsTokenized: false,
    IsProcessed: true,
  },
  {
    Isin: "INE945W07399",
    MbeId: "rajkumar@inclusivegrowthchain.com",
    IssuerName: "INCRED FINANCIAL SERVICES LIMITED",
    CouponRate: "9.25%",
    FaceValue: 1,
    Ltp: 0.971,
    CreditRating: "CRISIL A+/Stable ()",
    MaturityDate: "18-02-2024",
    SecurityDescription:
      "INCRED FINANCIAL SERVICES LIMITED SR 2 9.25 NCD 18FB24 FVRS1000",
    Currency: "Rupee",
    noOfLots: 6,
    TokenizedLot: 4,
    TotalTokenQty: 800000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    IsTokenized: false,
    IsProcessed: true,
  },
  {
    Isin: "INE884Q07061",
    MbeId: "prudhvi@inclusivegrowthchain.com",
    IssuerName: "MIDLAND MICROFIN LIMITED",
    CouponRate: "12%",
    FaceValue: 1,
    Ltp: 0.89,
    CreditRating: "CARE BBB/Positive ()",
    MaturityDate: "04-01-2024",
    SecurityDescription:
      "MIDLAND MICROFIN LIMITED OPT 6 12 NCD 04JN24 FVRS10000",
    Currency: "Rupee",
    noOfLots: 4,
    TokenizedLot: 1,
    TotalTokenQty: 200000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    IsTokenized: false,
    IsProcessed: true,
  },
  {
    Isin: "INE721A07PE0",
    MbeId: "shreyanshnema@inclusivegrowthchain.com",
    IssuerName: "SHRIRAM FINANCE LIMITED",
    CouponRate: "9.70%",
    FaceValue: 1,
    Ltp: 1.11,
    CreditRating: "CARE AA+/Stable ();IND AA+/Stable ();CRISIL AA+/Stable",
    MaturityDate: "22-08-2026",
    SecurityDescription:
      "SHRIRAM FINANCE LIMITED SERIES VII NCD 9.70 22AG26 FVRS1000",
    Currency: "Rupee",
    noOfLots: 4,
    TokenizedLot: 3,
    TotalTokenQty: 600000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    IsTokenized: false,
    IsProcessed: true,
  },
  {
    Isin: "INE651J07606",
    MbeId: "rishav.goenka@inclusivegrowthchain.com",
    IssuerName: "JM FINANCIAL CREDIT SOLUTIONS LIMITED",
    CouponRate: "9.50%",
    FaceValue: 1,
    Ltp: 0.88,
    CreditRating: "IND AA/Stable ();ICRA AA/Stable",
    MaturityDate: "07-06-2023",
    SecurityDescription:
      "JM FINANCIAL CREDIT SOLUTIONS LIMITED TR 1 OPT III 9.5 NCD 07JU23 FVRS1000",
    Currency: "Rupee",
    noOfLots: 9,
    TokenizedLot: 6,
    TotalTokenQty: 1200000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    IsTokenized: false,
    IsProcessed: true,
  },
  {
    Isin: "INE583D07240",
    MbeId: "prudhvi@inclusivegrowthchain.com",
    IssuerName: "UGRO CAPITAL LIMITED",
    CouponRate: "10%",
    FaceValue: 1,
    Ltp: 1,
    CreditRating: "ACUITE A/Stable ()",
    MaturityDate: "04-11-2023",
    SecurityDescription: "UGRO CAPITAL LIMITED SR I 10 NCD 04NV23 FVRS1000",
    Currency: "Rupee",
    noOfLots: 6,
    TokenizedLot: 4,
    TotalTokenQty: 800000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    IsTokenized: false,
    IsProcessed: true,
  },
].map((f, i) => ({ id: i, ...f }))

export default bond