const bond = [
  {
    isin: "INE00XE07101",
    mbeId: "muhsin@inclusivegrowthchain.com",
    issuerName: "MUTHOOT VEHICLE & ASSET FINANCE LIMITED",
    couponRate: "9.50%",
    faceValue: 1,
    ltp: 1.015,
    creditRating: "CRISIL A/Stable;CARE BBB+",
    maturityDate: "17-05-2023",
    securityDescription:
      "MUTHOOT VEHICLE & ASSET FINANCE LIMITED OPTION II 9.50 NCD 17MY23 FVRS1000",
    Currency: "Rupee",
    noOfLots: 2,
    tokenizedLot: 1,
    totalTokenQty: 200000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    isTokenized: false,
    isProcessed: true,
  },
  {
    isin: "INE01I507042",
    mbeId: "shreyanshnema@inclusivegrowthchain.com",
    issuerName: "KLM AXIVA FINVEST LIMITED",
    couponRate: "12.00%",
    faceValue: 1,
    ltp: 0.98,
    creditRating: "CARE BB+/Stable",
    maturityDate: "05-11-2023",
    securityDescription:
      "KLM AXIVA FINVEST LIMITED OPT IV 12 LOA 05NV23 FVRS1000",
    Currency: "Rupee",
    noOfLots: 1,
    tokenizedLot: 0,
    totalTokenQty: 0,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    isTokenized: false,
    isProcessed: true,
  },
  {
    isin: "INE027E07923",
    mbeId: "rajkumar@inclusivegrowthchain.com",
    issuerName: "L&T FINANCE LIMITED",
    couponRate: "9.10%",
    faceValue: 1,
    ltp: 1.12,
    creditRating: "IND AAA/Stable;ICRA AAA/Stable;CARE AAA/Stable",
    maturityDate: "08-09-2032",
    securityDescription:
      "L&T FINANCE LIMITED SR III OPT 1 9.1 LOA 13MR24 FVRS1000",
    Currency: "Rupee",
    noOfLots: 4,
    tokenizedLot: 2,
    totalTokenQty: 400000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    isTokenized: false,
    isProcessed: true,
  },
  {
    isin: "INE033L07FZ3",
    mbeId: "prudhvi@inclusivegrowthchain.com",
    issuerName: "TATA CAPITAL HOUSING FINANCE LIMITED",
    couponRate: "8.80%",
    faceValue: 1,
    ltp: 0.89,
    creditRating: "CRISIL AAA/Stable",
    maturityDate: "25-09-2023",
    securityDescription:
      "TATA CAPITAL HOUSING FINANCE LIMITED 8.8 NCD 25SP23 FVRS1000",
    Currency: "Rupee",
    noOfLots: 3,
    tokenizedLot: 2,
    totalTokenQty: 400000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    isTokenized: false,
    isProcessed: true,
  },
  {
    isin: "INE101Q07391",
    mbeId: "rishav.goenka@inclusivegrowthchain.com",
    issuerName: "MUTHOOTTU MINI FINANCIERS LTD",
    couponRate: "10.00%",
    faceValue: 1,
    ltp: 0.99,
    creditRating: "IND A-/Stable",
    maturityDate: "24-04-2024",
    securityDescription:
      "MUTHOOTTU MINI FINANCIERS LTD SERIES VIII-V 10 NCD 24AP24 FVRS1000",
    Currency: "Rupee",
    noOfLots: 5,
    tokenizedLot: 3,
    totalTokenQty: 600000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    isTokenized: false,
    isProcessed: true,
  },
  {
    isin: "INE039A07801",
    mbeId: "muhsin@inclusivegrowthchain.com",
    issuerName: "IFCI LIMITED",
    couponRate: "9.90%",
    faceValue: 1,
    ltp: 1.14,
    creditRating: "ICRA B+/Negative;BWR BB/Negative",
    maturityDate: "01-12-2024",
    securityDescription:
      "IFCI LIMITED SR-VI 9.9 NCD 01DC24 FVRS1000 LOA UPTO 17MY15",
    Currency: "Rupee",
    noOfLots: 2,
    tokenizedLot: 1,
    totalTokenQty: 200000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    isTokenized: false,
    isProcessed: true,
  },
  {
    isin: "INE217K07AF7",
    mbeId: "shreyanshnema@inclusivegrowthchain.com",
    issuerName: "RELIANCE HOME FINANCE LIMITED",
    couponRate: "9.00%",
    faceValue: 1,
    ltp: 0.98,
    creditRating: "CRISIL AAA / Stable",
    maturityDate: "04-11-2025",
    securityDescription:
      "RELIANCE HOME FINANCE LIMITED SR-III CAT I & II 9 NCD 03JN27 FVRS1000",
    Currency: "Rupee",
    noOfLots: 4,
    tokenizedLot: 2,
    totalTokenQty: 400000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    isTokenized: false,
    isProcessed: true,
  },
  {
    isin: "INE219X07173",
    mbeId: "rajkumar@inclusivegrowthchain.com",
    issuerName: "INDIA GRID TRUST",
    couponRate: "6.65%",
    faceValue: 1,
    ltp: 1.25,
    creditRating: "IND AAA/Stable ;CRISIL AAA/Stable",
    maturityDate: "06-05-2024",
    securityDescription:
      "INDIA GRID TRUST SR I CAT I&II 6.65 NCD 06MY24 FVRS1000",
    Currency: "Rupee",
    noOfLots: 3,
    tokenizedLot: 1,
    totalTokenQty: 200000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    isTokenized: false,
    isProcessed: true,
  },
  {
    isin: "INE342T07189",
    mbeId: "prudhvi@inclusivegrowthchain.com",
    issuerName: "NAVI FINSERV LIMITED",
    couponRate: "9.20%",
    faceValue: 1,
    ltp: 0.79,
    creditRating: "IND A/Stable",
    maturityDate: "28-03-2024",
    securityDescription: "NAVI FINSERV LIMITED SR I 9.20 NCD 08DC23 FVRS1000",
    Currency: "Rupee",
    noOfLots: 1,
    tokenizedLot: 1,
    totalTokenQty: 200000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    isTokenized: false,
    isProcessed: true,
  },
  {
    isin: "INE774D07ST5",
    mbeId: "rishav.goenka@inclusivegrowthchain.com",
    issuerName: "MAHINDRA & MAHINDRA FINANCIAL SERVICES LTD",
    couponRate: "9.10%",
    faceValue: 1,
    ltp: 1.311,
    creditRating: "IND AAA/Stable ;CARE AAA/Stable",
    maturityDate: "18-01-2024",
    securityDescription:
      "MAHINDRA & MAHINDRA FINANCIAL SERVICES LTD SRIICATI&II9.10NCD 18JN24FV1000 LOAUPTO21JN19",
    Currency: "Rupee",
    noOfLots: 5,
    tokenizedLot: 4,
    totalTokenQty: 800000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    isTokenized: false,
    isProcessed: true,
  },
  {
    isin: "INE804I075Y4",
    mbeId: "muhsin@inclusivegrowthchain.com",
    issuerName: "ECL FINANCE LIMITED",
    couponRate: "9.25%",
    faceValue: 1,
    ltp: 0.87,
    creditRating: "CRISIL AA-/Negative;ICRA A+/Stable ()",
    maturityDate: "06-08-2023",
    securityDescription: "ECL FINANCE LIMITED SR-III 9.25 NCD 06AG23 FVRS1000",
    Currency: "Rupee",
    noOfLots: 1,
    tokenizedLot: 0,
    totalTokenQty: 0,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    isTokenized: false,
    isProcessed: true,
  },
  {
    isin: "INE872A07UQ5",
    mbeId: "shreyanshnema@inclusivegrowthchain.com",
    issuerName: "SREI EQUIPMENT FINANCE LIMITED",
    couponRate: "8.65%",
    faceValue: 1,
    ltp: 1.31,
    creditRating: "BWR D",
    maturityDate: "16-03-2023",
    securityDescription:
      "SREI EQUIPMENT FINANCE LTD SR-VI 8.65 LOA 16MR23 FVRS1000",
    Currency: "Rupee",
    noOfLots: 4,
    tokenizedLot: 2,
    totalTokenQty: 400000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    isTokenized: false,
    isProcessed: true,
  },
  {
    isin: "INE918K07FP8",
    mbeId: "rajkumar@inclusivegrowthchain.com",
    issuerName: "NUVAMA WEALTH FINANCE LIMITED",
    couponRate: "10%",
    faceValue: 1,
    ltp: 1.05,
    creditRating: "CRISIL AA-/Stable;CARE AA-/Stable ()",
    maturityDate: "05-02-2023",
    securityDescription:
      "NUVAMA WEALTH FINANCE LIMITED SR III 10 NCD 05FB23 FVRS1000",
    Currency: "Rupee",
    noOfLots: 3,
    tokenizedLot: 1,
    totalTokenQty: 200000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    isTokenized: false,
    isProcessed: true,
  },
  {
    isin: "INE945W07399",
    mbeId: "prudhvi@inclusivegrowthchain.com",
    issuerName: "INCRED FINANCIAL SERVICES LIMITED",
    couponRate: "9.25%",
    faceValue: 1,
    ltp: 0.971,
    creditRating: "CRISIL A+/Stable ()",
    maturityDate: "18-02-2024",
    securityDescription:
      "INCRED FINANCIAL SERVICES LIMITED SR 2 9.25 NCD 18FB24 FVRS1000",
    Currency: "Rupee",
    noOfLots: 2,
    tokenizedLot: 1,
    totalTokenQty: 200000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    isTokenized: false,
    isProcessed: true,
  },
  {
    isin: "INE884Q07061",
    mbeId: "rishav.goenka@inclusivegrowthchain.com",
    issuerName: "MIDLAND MICROFIN LIMITED",
    couponRate: "12%",
    faceValue: 1,
    ltp: 0.89,
    creditRating: "CARE BBB/Positive ()",
    maturityDate: "04-01-2024",
    securityDescription:
      "MIDLAND MICROFIN LIMITED OPT 6 12 NCD 04JN24 FVRS10000",
    Currency: "Rupee",
    noOfLots: 4,
    tokenizedLot: 2,
    totalTokenQty: 400000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    isTokenized: false,
    isProcessed: true,
  },
  {
    isin: "INE866I08279",
    mbeId: "muhsin@inclusivegrowthchain.com",
    issuerName: "IIFL FINANCE LIMITED",
    couponRate: "10%",
    faceValue: 1,
    ltp: 1.16,
    creditRating: "CRISIL AA/Stable;ICRA AA/Stable;BWR AA+/Stable",
    maturityDate: "07-02-2029",
    securityDescription: "IIFL FINANCE LIMITED SR V 10 NCD 07FB29 FVRS1000",
    Currency: "Rupee",
    noOfLots: 6,
    tokenizedLot: 3,
    totalTokenQty: 600000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    isTokenized: false,
    isProcessed: true,
  },
  {
    isin: "INE774D08LT8",
    mbeId: "shreyanshnema@inclusivegrowthchain.com",
    issuerName: "MAHINDRA & MAHINDRA FINANCIAL SERVICES LTD",
    couponRate: "8.53%",
    faceValue: 1,
    ltp: 1,
    creditRating: "IND AAA/Stable ();CARE AAA/Stable ()",
    maturityDate: "06-06-2026",
    securityDescription:
      "MAHINDRA & MAHINDRA FINANCIAL SERVICES LTD SR-III8.53 NCD06JU26FVRS1000LOAUPTO24JL16",
    Currency: "Rupee",
    noOfLots: 10,
    tokenizedLot: 6,
    totalTokenQty: 1200000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    isTokenized: false,
    isProcessed: true,
  },
  {
    isin: "INE721A07PE0",
    mbeId: "rajkumar@inclusivegrowthchain.com",
    issuerName: "SHRIRAM FINANCE LIMITED",
    couponRate: "9.70%",
    faceValue: 1,
    ltp: 1.11,
    creditRating: "CARE AA+/Stable ();IND AA+/Stable ();CRISIL AA+/Stable",
    maturityDate: "22-08-2026",
    securityDescription:
      "SHRIRAM FINANCE LIMITED SERIES VII NCD 9.70 22AG26 FVRS1000",
    Currency: "Rupee",
    noOfLots: 2,
    tokenizedLot: 1,
    totalTokenQty: 200000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    isTokenized: false,
    isProcessed: true,
  },
  {
    isin: "INE651J07606",
    mbeId: "prudhvi@inclusivegrowthchain.com",
    issuerName: "JM FINANCIAL CREDIT SOLUTIONS LIMITED",
    couponRate: "9.50%",
    faceValue: 1,
    ltp: 0.88,
    creditRating: "IND AA/Stable ();ICRA AA/Stable",
    maturityDate: "07-06-2023",
    securityDescription:
      "JM FINANCIAL CREDIT SOLUTIONS LIMITED TR 1 OPT III 9.5 NCD 07JU23 FVRS1000",
    Currency: "Rupee",
    noOfLots: 3,
    tokenizedLot: 3,
    totalTokenQty: 600000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    isTokenized: false,
    isProcessed: true,
  },
  {
    isin: "INE583D07240",
    mbeId: "rishav.goenka@inclusivegrowthchain.com",
    issuerName: "UGRO CAPITAL LIMITED",
    couponRate: "10%",
    faceValue: 1,
    ltp: 1,
    creditRating: "ACUITE A/Stable ()",
    maturityDate: "04-11-2023",
    securityDescription: "UGRO CAPITAL LIMITED SR I 10 NCD 04NV23 FVRS1000",
    Currency: "Rupee",
    noOfLots: 4,
    tokenizedLot: 2,
    totalTokenQty: 400000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    isTokenized: false,
    isProcessed: true,
  },
  {
    isin: "INE01I507042",
    mbeId: "prudhvi@inclusivegrowthchain.com",
    issuerName: "KLM AXIVA FINVEST LIMITED",
    couponRate: "12.00%",
    faceValue: 1,
    ltp: 0.98,
    creditRating: "CARE BB+/Stable",
    maturityDate: "05-11-2023",
    securityDescription:
      "KLM AXIVA FINVEST LIMITED OPT IV 12 LOA 05NV23 FVRS1000",
    Currency: "Rupee",
    noOfLots: 1,
    tokenizedLot: 0,
    totalTokenQty: 0,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    isTokenized: false,
    isProcessed: true,
  },
  {
    isin: "INE033L07FZ3",
    mbeId: "shreyanshnema@inclusivegrowthchain.com",
    issuerName: "TATA CAPITAL HOUSING FINANCE LIMITED",
    couponRate: "8.80%",
    faceValue: 1,
    ltp: 0.89,
    creditRating: "CRISIL AAA/Stable",
    maturityDate: "25-09-2023",
    securityDescription:
      "TATA CAPITAL HOUSING FINANCE LIMITED 8.8 NCD 25SP23 FVRS1000",
    Currency: "Rupee",
    noOfLots: 3,
    tokenizedLot: 2,
    totalTokenQty: 400000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    isTokenized: false,
    isProcessed: true,
  },
  {
    isin: "INE039A07801",
    mbeId: "rishav.goenka@inclusivegrowthchain.com",
    issuerName: "IFCI LIMITED",
    couponRate: "9.90%",
    faceValue: 1,
    ltp: 1.14,
    creditRating: "ICRA B+/Negative;BWR BB/Negative",
    maturityDate: "01-12-2024",
    securityDescription:
      "IFCI LIMITED SR-VI 9.9 NCD 01DC24 FVRS1000 LOA UPTO 17MY15",
    Currency: "Rupee",
    noOfLots: 2,
    tokenizedLot: 1,
    totalTokenQty: 200000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    isTokenized: false,
    isProcessed: true,
  },
  {
    isin: "INE217K07AF7",
    mbeId: "prudhvi@inclusivegrowthchain.com",
    issuerName: "RELIANCE HOME FINANCE LIMITED",
    couponRate: "9.00%",
    faceValue: 1,
    ltp: 0.98,
    creditRating: "CRISIL AAA / Stable",
    maturityDate: "04-11-2025",
    securityDescription:
      "RELIANCE HOME FINANCE LIMITED SR-III CAT I & II 9 NCD 03JN27 FVRS1000",
    Currency: "Rupee",
    noOfLots: 4,
    tokenizedLot: 1,
    totalTokenQty: 200000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    isTokenized: false,
    isProcessed: true,
  },
  {
    isin: "INE342T07189",
    mbeId: "shreyanshnema@inclusivegrowthchain.com",
    issuerName: "NAVI FINSERV LIMITED",
    couponRate: "9.20%",
    faceValue: 1,
    ltp: 0.79,
    creditRating: "IND A/Stable",
    maturityDate: "28-03-2024",
    securityDescription: "NAVI FINSERV LIMITED SR I 9.20 NCD 08DC23 FVRS1000",
    Currency: "Rupee",
    noOfLots: 1,
    tokenizedLot: 0,
    totalTokenQty: 0,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    isTokenized: false,
    isProcessed: true,
  },
  {
    isin: "INE774D07ST5",
    mbeId: "muhsin@inclusivegrowthchain.com",
    issuerName: "MAHINDRA & MAHINDRA FINANCIAL SERVICES LTD",
    couponRate: "9.10%",
    faceValue: 1,
    ltp: 1.311,
    creditRating: "IND AAA/Stable ;CARE AAA/Stable",
    maturityDate: "18-01-2024",
    securityDescription:
      "MAHINDRA & MAHINDRA FINANCIAL SERVICES LTD SRIICATI&II9.10NCD 18JN24FV1000 LOAUPTO21JN19",
    Currency: "Rupee",
    noOfLots: 5,
    tokenizedLot: 3,
    totalTokenQty: 600000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    isTokenized: false,
    isProcessed: true,
  },
  {
    isin: "INE804I075Y4",
    mbeId: "rishav.goenka@inclusivegrowthchain.com",
    issuerName: "ECL FINANCE LIMITED",
    couponRate: "9.25%",
    faceValue: 1,
    ltp: 0.87,
    creditRating: "CRISIL AA-/Negative;ICRA A+/Stable ()",
    maturityDate: "06-08-2023",
    securityDescription: "ECL FINANCE LIMITED SR-III 9.25 NCD 06AG23 FVRS1000",
    Currency: "Rupee",
    noOfLots: 1,
    tokenizedLot: 1,
    totalTokenQty: 200000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    isTokenized: false,
    isProcessed: true,
  },
  {
    isin: "INE872A07UQ5",
    mbeId: "prudhvi@inclusivegrowthchain.com",
    issuerName: "SREI EQUIPMENT FINANCE LIMITED",
    couponRate: "8.65%",
    faceValue: 1,
    ltp: 1.31,
    creditRating: "BWR D",
    maturityDate: "16-03-2023",
    securityDescription:
      "SREI EQUIPMENT FINANCE LTD SR-VI 8.65 LOA 16MR23 FVRS1000",
    Currency: "Rupee",
    noOfLots: 4,
    tokenizedLot: 2,
    totalTokenQty: 400000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    isTokenized: false,
    isProcessed: true,
  },
  {
    isin: "INE945W07399",
    mbeId: "shreyanshnema@inclusivegrowthchain.com",
    issuerName: "INCRED FINANCIAL SERVICES LIMITED",
    couponRate: "9.25%",
    faceValue: 1,
    ltp: 0.971,
    creditRating: "CRISIL A+/Stable ()",
    maturityDate: "18-02-2024",
    securityDescription:
      "INCRED FINANCIAL SERVICES LIMITED SR 2 9.25 NCD 18FB24 FVRS1000",
    Currency: "Rupee",
    noOfLots: 2,
    tokenizedLot: 1,
    totalTokenQty: 200000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    isTokenized: false,
    isProcessed: true,
  },
  {
    isin: "INE884Q07061",
    mbeId: "muhsin@inclusivegrowthchain.com",
    issuerName: "MIDLAND MICROFIN LIMITED",
    couponRate: "12%",
    faceValue: 1,
    ltp: 0.89,
    creditRating: "CARE BBB/Positive ()",
    maturityDate: "04-01-2024",
    securityDescription:
      "MIDLAND MICROFIN LIMITED OPT 6 12 NCD 04JN24 FVRS10000",
    Currency: "Rupee",
    noOfLots: 4,
    tokenizedLot: 3,
    totalTokenQty: 600000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    isTokenized: false,
    isProcessed: true,
  },
  {
    isin: "INE866I08279",
    mbeId: "rishav.goenka@inclusivegrowthchain.com",
    issuerName: "IIFL FINANCE LIMITED",
    couponRate: "10%",
    faceValue: 1,
    ltp: 1.16,
    creditRating: "CRISIL AA/Stable;ICRA AA/Stable;BWR AA+/Stable",
    maturityDate: "07-02-2029",
    securityDescription: "IIFL FINANCE LIMITED SR V 10 NCD 07FB29 FVRS1000",
    Currency: "Rupee",
    noOfLots: 6,
    tokenizedLot: 3,
    totalTokenQty: 600000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    isTokenized: false,
    isProcessed: true,
  },
  {
    isin: "INE651J07606",
    mbeId: "shreyanshnema@inclusivegrowthchain.com",
    issuerName: "JM FINANCIAL CREDIT SOLUTIONS LIMITED",
    couponRate: "9.50%",
    faceValue: 1,
    ltp: 0.88,
    creditRating: "IND AA/Stable ();ICRA AA/Stable",
    maturityDate: "07-06-2023",
    securityDescription:
      "JM FINANCIAL CREDIT SOLUTIONS LIMITED TR 1 OPT III 9.5 NCD 07JU23 FVRS1000",
    Currency: "Rupee",
    noOfLots: 3,
    tokenizedLot: 3,
    totalTokenQty: 600000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    isTokenized: false,
    isProcessed: true,
  },
  {
    isin: "INE583D07240",
    mbeId: "muhsin@inclusivegrowthchain.com",
    issuerName: "UGRO CAPITAL LIMITED",
    couponRate: "10%",
    faceValue: 1,
    ltp: 1,
    creditRating: "ACUITE A/Stable ()",
    maturityDate: "04-11-2023",
    securityDescription: "UGRO CAPITAL LIMITED SR I 10 NCD 04NV23 FVRS1000",
    Currency: "Rupee",
    noOfLots: 4,
    tokenizedLot: 2,
    totalTokenQty: 400000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    isTokenized: false,
    isProcessed: true,
  },
  {
    isin: "INE01I507042",
    mbeId: "muhsin@inclusivegrowthchain.com",
    issuerName: "KLM AXIVA FINVEST LIMITED",
    couponRate: "12.00%",
    faceValue: 1,
    ltp: 0.98,
    creditRating: "CARE BB+/Stable",
    maturityDate: "05-11-2023",
    securityDescription:
      "KLM AXIVA FINVEST LIMITED OPT IV 12 LOA 05NV23 FVRS1000",
    Currency: "Rupee",
    noOfLots: 4,
    tokenizedLot: 3,
    totalTokenQty: 600000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    isTokenized: false,
    isProcessed: true,
  },
  {
    isin: "INE027E07923",
    mbeId: "rishav.goenka@inclusivegrowthchain.com",
    issuerName: "L&T FINANCE LIMITED",
    couponRate: "9.10%",
    faceValue: 1,
    ltp: 1.12,
    creditRating: "IND AAA/Stable;ICRA AAA/Stable;CARE AAA/Stable",
    maturityDate: "08-09-2032",
    securityDescription:
      "L&T FINANCE LIMITED SR III OPT 1 9.1 LOA 13MR24 FVRS1000",
    Currency: "Rupee",
    noOfLots: 6,
    tokenizedLot: 2,
    totalTokenQty: 400000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    isTokenized: false,
    isProcessed: true,
  },
  {
    isin: "INE033L07FZ3",
    mbeId: "rajkumar@inclusivegrowthchain.com",
    issuerName: "TATA CAPITAL HOUSING FINANCE LIMITED",
    couponRate: "8.80%",
    faceValue: 1,
    ltp: 0.89,
    creditRating: "CRISIL AAA/Stable",
    maturityDate: "25-09-2023",
    securityDescription:
      "TATA CAPITAL HOUSING FINANCE LIMITED 8.8 NCD 25SP23 FVRS1000",
    Currency: "Rupee",
    noOfLots: 9,
    tokenizedLot: 5,
    totalTokenQty: 1000000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    isTokenized: false,
    isProcessed: true,
  },
  {
    isin: "INE101Q07391",
    mbeId: "prudhvi@inclusivegrowthchain.com",
    issuerName: "MUTHOOTTU MINI FINANCIERS LTD",
    couponRate: "10.00%",
    faceValue: 1,
    ltp: 0.99,
    creditRating: "IND A-/Stable",
    maturityDate: "24-04-2024",
    securityDescription:
      "MUTHOOTTU MINI FINANCIERS LTD SERIES VIII-V 10 NCD 24AP24 FVRS1000",
    Currency: "Rupee",
    noOfLots: 10,
    tokenizedLot: 4,
    totalTokenQty: 800000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    isTokenized: false,
    isProcessed: true,
  },
  {
    isin: "INE217K07AF7",
    mbeId: "muhsin@inclusivegrowthchain.com",
    issuerName: "RELIANCE HOME FINANCE LIMITED",
    couponRate: "9.00%",
    faceValue: 1,
    ltp: 0.98,
    creditRating: "CRISIL AAA / Stable",
    maturityDate: "04-11-2025",
    securityDescription:
      "RELIANCE HOME FINANCE LIMITED SR-III CAT I & II 9 NCD 03JN27 FVRS1000",
    Currency: "Rupee",
    noOfLots: 6,
    tokenizedLot: 4,
    totalTokenQty: 800000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    isTokenized: false,
    isProcessed: true,
  },
  {
    isin: "INE219X07173",
    mbeId: "shreyanshnema@inclusivegrowthchain.com",
    issuerName: "INDIA GRID TRUST",
    couponRate: "6.65%",
    faceValue: 1,
    ltp: 1.25,
    creditRating: "IND AAA/Stable ;CRISIL AAA/Stable",
    maturityDate: "06-05-2024",
    securityDescription:
      "INDIA GRID TRUST SR I CAT I&II 6.65 NCD 06MY24 FVRS1000",
    Currency: "Rupee",
    noOfLots: 1,
    tokenizedLot: 1,
    totalTokenQty: 200000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    isTokenized: false,
    isProcessed: true,
  },
  {
    isin: "INE342T07189",
    mbeId: "rishav.goenka@inclusivegrowthchain.com",
    issuerName: "NAVI FINSERV LIMITED",
    couponRate: "9.20%",
    faceValue: 1,
    ltp: 0.79,
    creditRating: "IND A/Stable",
    maturityDate: "28-03-2024",
    securityDescription: "NAVI FINSERV LIMITED SR I 9.20 NCD 08DC23 FVRS1000",
    Currency: "Rupee",
    noOfLots: 4,
    tokenizedLot: 0,
    totalTokenQty: 0,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    isTokenized: false,
    isProcessed: true,
  },
  {
    isin: "INE774D07ST5",
    mbeId: "prudhvi@inclusivegrowthchain.com",
    issuerName: "MAHINDRA & MAHINDRA FINANCIAL SERVICES LTD",
    couponRate: "9.10%",
    faceValue: 1,
    ltp: 1.311,
    creditRating: "IND AAA/Stable ;CARE AAA/Stable",
    maturityDate: "18-01-2024",
    securityDescription:
      "MAHINDRA & MAHINDRA FINANCIAL SERVICES LTD SRIICATI&II9.10NCD 18JN24FV1000 LOAUPTO21JN19",
    Currency: "Rupee",
    noOfLots: 2,
    tokenizedLot: 2,
    totalTokenQty: 400000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    isTokenized: false,
    isProcessed: true,
  },
  {
    isin: "INE872A07UQ5",
    mbeId: "muhsin@inclusivegrowthchain.com",
    issuerName: "SREI EQUIPMENT FINANCE LIMITED",
    couponRate: "8.65%",
    faceValue: 1,
    ltp: 1.31,
    creditRating: "BWR D",
    maturityDate: "16-03-2023",
    securityDescription:
      "SREI EQUIPMENT FINANCE LTD SR-VI 8.65 LOA 16MR23 FVRS1000",
    Currency: "Rupee",
    noOfLots: 9,
    tokenizedLot: 6,
    totalTokenQty: 1200000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    isTokenized: false,
    isProcessed: true,
  },
  {
    isin: "INE918K07FP8",
    mbeId: "rishav.goenka@inclusivegrowthchain.com",
    issuerName: "NUVAMA WEALTH FINANCE LIMITED",
    couponRate: "10%",
    faceValue: 1,
    ltp: 1.05,
    creditRating: "CRISIL AA-/Stable;CARE AA-/Stable ()",
    maturityDate: "05-02-2023",
    securityDescription:
      "NUVAMA WEALTH FINANCE LIMITED SR III 10 NCD 05FB23 FVRS1000",
    Currency: "Rupee",
    noOfLots: 10,
    tokenizedLot: 8,
    totalTokenQty: 1600000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    isTokenized: false,
    isProcessed: true,
  },
  {
    isin: "INE945W07399",
    mbeId: "rajkumar@inclusivegrowthchain.com",
    issuerName: "INCRED FINANCIAL SERVICES LIMITED",
    couponRate: "9.25%",
    faceValue: 1,
    ltp: 0.971,
    creditRating: "CRISIL A+/Stable ()",
    maturityDate: "18-02-2024",
    securityDescription:
      "INCRED FINANCIAL SERVICES LIMITED SR 2 9.25 NCD 18FB24 FVRS1000",
    Currency: "Rupee",
    noOfLots: 6,
    tokenizedLot: 4,
    totalTokenQty: 800000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    isTokenized: false,
    isProcessed: true,
  },
  {
    isin: "INE884Q07061",
    mbeId: "prudhvi@inclusivegrowthchain.com",
    issuerName: "MIDLAND MICROFIN LIMITED",
    couponRate: "12%",
    faceValue: 1,
    ltp: 0.89,
    creditRating: "CARE BBB/Positive ()",
    maturityDate: "04-01-2024",
    securityDescription:
      "MIDLAND MICROFIN LIMITED OPT 6 12 NCD 04JN24 FVRS10000",
    Currency: "Rupee",
    noOfLots: 4,
    tokenizedLot: 1,
    totalTokenQty: 200000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    isTokenized: false,
    isProcessed: true,
  },
  {
    isin: "INE721A07PE0",
    mbeId: "shreyanshnema@inclusivegrowthchain.com",
    issuerName: "SHRIRAM FINANCE LIMITED",
    couponRate: "9.70%",
    faceValue: 1,
    ltp: 1.11,
    creditRating: "CARE AA+/Stable ();IND AA+/Stable ();CRISIL AA+/Stable",
    maturityDate: "22-08-2026",
    securityDescription:
      "SHRIRAM FINANCE LIMITED SERIES VII NCD 9.70 22AG26 FVRS1000",
    Currency: "Rupee",
    noOfLots: 4,
    tokenizedLot: 3,
    totalTokenQty: 600000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    isTokenized: false,
    isProcessed: true,
  },
  {
    isin: "INE651J07606",
    mbeId: "rishav.goenka@inclusivegrowthchain.com",
    issuerName: "JM FINANCIAL CREDIT SOLUTIONS LIMITED",
    couponRate: "9.50%",
    faceValue: 1,
    ltp: 0.88,
    creditRating: "IND AA/Stable ();ICRA AA/Stable",
    maturityDate: "07-06-2023",
    securityDescription:
      "JM FINANCIAL CREDIT SOLUTIONS LIMITED TR 1 OPT III 9.5 NCD 07JU23 FVRS1000",
    Currency: "Rupee",
    noOfLots: 9,
    tokenizedLot: 6,
    totalTokenQty: 1200000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    isTokenized: false,
    isProcessed: true,
  },
  {
    isin: "INE583D07240",
    mbeId: "prudhvi@inclusivegrowthchain.com",
    issuerName: "UGRO CAPITAL LIMITED",
    couponRate: "10%",
    faceValue: 1,
    ltp: 1,
    creditRating: "ACUITE A/Stable ()",
    maturityDate: "04-11-2023",
    securityDescription: "UGRO CAPITAL LIMITED SR I 10 NCD 04NV23 FVRS1000",
    Currency: "Rupee",
    noOfLots: 6,
    tokenizedLot: 4,
    totalTokenQty: 800000,
    totalTokenQtyRemaining: 0,
    purchasePrice: 0,
    currentPrice: 0,
    isTokenized: false,
    isProcessed: true,
  },
].map((f, i) => ({ id: i, ...f }))

export default bond