import getRandom from '../helper/getRandom';

const type = ["Tokenized", "Detokenized", "Trade"]
const status = ["Success", "Failure", "Pending"]
const authorisedStaus = ["Authorised", "Pending"]

const custodianTransaction = [
  {
    id: "1",
    maturityDate: "30-01-2022",
    transactionNo: getRandom(10, 100),
    transactionType: type[getRandom(0, 2)],
    status: status[getRandom(0, 2)],
    authorisedStaus: authorisedStaus[getRandom(0, 1)],
  },
  {
    id: "2",
    maturityDate: "29-02-2022",
    transactionNo: getRandom(10, 100),
    transactionType: type[getRandom(0, 2)],
    status: status[getRandom(0, 2)],
    authorisedStaus: authorisedStaus[getRandom(0, 1)],
  },
  {
    id: "3",
    maturityDate: "08-03-2022",
    transactionNo: getRandom(10, 100),
    transactionType: type[getRandom(0, 2)],
    status: status[getRandom(0, 2)],
    authorisedStaus: authorisedStaus[getRandom(0, 1)],
  },
  {
    id: "4",
    maturityDate: "26-04-2022",
    transactionNo: getRandom(10, 100),
    transactionType: type[getRandom(0, 2)],
    status: status[getRandom(0, 2)],
    authorisedStaus: authorisedStaus[getRandom(0, 1)],
  },
  {
    id: "5",
    maturityDate: "28-04-2022",
    transactionNo: getRandom(10, 100),
    transactionType: type[getRandom(0, 2)],
    status: status[getRandom(0, 2)],
    authorisedStaus: authorisedStaus[getRandom(0, 1)],
  },
  {
    id: "6",
    maturityDate: "21-05-2022",
    transactionNo: getRandom(10, 100),
    transactionType: type[getRandom(0, 2)],
    status: status[getRandom(0, 2)],
    authorisedStaus: authorisedStaus[getRandom(0, 1)],
  },
  {
    id: "7",
    maturityDate: "24-05-2022",
    transactionNo: getRandom(10, 100),
    transactionType: type[getRandom(0, 2)],
    status: status[getRandom(0, 2)],
    authorisedStaus: authorisedStaus[getRandom(0, 1)],
  },
  {
    id: "8",
    maturityDate: "17-06-2022",
    transactionNo: getRandom(10, 100),
    transactionType: type[getRandom(0, 2)],
    status: status[getRandom(0, 2)],
    authorisedStaus: authorisedStaus[getRandom(0, 1)],
  },
  {
    id: "9",
    maturityDate: "28-06-2022",
    transactionNo: getRandom(10, 100),
    transactionType: type[getRandom(0, 2)],
    status: status[getRandom(0, 2)],
    authorisedStaus: authorisedStaus[getRandom(0, 1)],
  },
  {
    id: "10",
    maturityDate: "30-07-2022",
    transactionNo: getRandom(10, 100),
    transactionType: type[getRandom(0, 2)],
    status: status[getRandom(0, 2)],
    authorisedStaus: authorisedStaus[getRandom(0, 1)],
  },
  {
    id: "11",
    maturityDate: "07-08-2022",
    transactionNo: getRandom(10, 100),
    transactionType: type[getRandom(0, 2)],
    status: status[getRandom(0, 2)],
    authorisedStaus: authorisedStaus[getRandom(0, 1)],
  },
  {
    id: "12",
    maturityDate: "20-07-2022",
    transactionNo: getRandom(10, 100),
    transactionType: type[getRandom(0, 2)],
    status: status[getRandom(0, 2)],
    authorisedStaus: authorisedStaus[getRandom(0, 1)],
  },
  {
    id: "13",
    maturityDate: "09-08-2022",
    transactionNo: getRandom(10, 100),
    transactionType: type[getRandom(0, 2)],
    status: status[getRandom(0, 2)],
    authorisedStaus: authorisedStaus[getRandom(0, 1)],
  },
  {
    id: "14",
    maturityDate: "13-08-2022",
    transactionNo: getRandom(10, 100),
    transactionType: type[getRandom(0, 2)],
    status: status[getRandom(0, 2)],
    authorisedStaus: authorisedStaus[getRandom(0, 1)],
  },
  {
    id: "15",
    maturityDate: "17-08-2022",
    transactionNo: getRandom(10, 100),
    transactionType: type[getRandom(0, 2)],
    status: status[getRandom(0, 2)],
    authorisedStaus: authorisedStaus[getRandom(0, 1)],
  },
  {
    id: "16",
    maturityDate: "19-09-2022",
    transactionNo: getRandom(10, 100),
    transactionType: type[getRandom(0, 2)],
    status: status[getRandom(0, 2)],
    authorisedStaus: authorisedStaus[getRandom(0, 1)],
  },
  {
    id: "17",
    maturityDate: "05-10-2022",
    transactionNo: getRandom(10, 100),
    transactionType: type[getRandom(0, 2)],
    status: status[getRandom(0, 2)],
    authorisedStaus: authorisedStaus[getRandom(0, 1)],
  },
  {
    id: "18",
    maturityDate: "13-10-2022",
    transactionNo: getRandom(10, 100),
    transactionType: type[getRandom(0, 2)],
    status: status[getRandom(0, 2)],
    authorisedStaus: authorisedStaus[getRandom(0, 1)],
  },
  {
    id: "19",
    maturityDate: "28-10-2022",
    transactionNo: getRandom(10, 100),
    transactionType: type[getRandom(0, 2)],
    status: status[getRandom(0, 2)],
    authorisedStaus: authorisedStaus[getRandom(0, 1)],
  },
  {
    id: "20",
    maturityDate: "06-12-2022",
    transactionNo: getRandom(10, 100),
    transactionType: type[getRandom(0, 2)],
    status: status[getRandom(0, 2)],
    authorisedStaus: authorisedStaus[getRandom(0, 1)],
  },
]

export default custodianTransaction