import getRandom from '../helper/getRandom';

const type = ["Tokenized", "Detokenized", "Trade"]
const status = ["Success", "Failure", "Pending"]
const authorisedStaus = ["Authorised", "Pending"]

const custodianTransaction = [
  {
    id: "1",
    MaturityDate: "30-01-2022",
    transactionNo: getRandom(10, 100),
    TransactionsType: type[getRandom(0, 2)],
    status: status[getRandom(0, 2)],
    authorisedStaus: authorisedStaus[getRandom(0, 1)],
  },
  {
    id: "2",
    MaturityDate: "29-02-2022",
    transactionNo: getRandom(10, 100),
    TransactionsType: type[getRandom(0, 2)],
    status: status[getRandom(0, 2)],
    authorisedStaus: authorisedStaus[getRandom(0, 1)],
  },
  {
    id: "3",
    MaturityDate: "08-03-2022",
    transactionNo: getRandom(10, 100),
    TransactionsType: type[getRandom(0, 2)],
    status: status[getRandom(0, 2)],
    authorisedStaus: authorisedStaus[getRandom(0, 1)],
  },
  {
    id: "4",
    MaturityDate: "26-04-2022",
    transactionNo: getRandom(10, 100),
    TransactionsType: type[getRandom(0, 2)],
    status: status[getRandom(0, 2)],
    authorisedStaus: authorisedStaus[getRandom(0, 1)],
  },
  {
    id: "5",
    MaturityDate: "28-04-2022",
    transactionNo: getRandom(10, 100),
    TransactionsType: type[getRandom(0, 2)],
    status: status[getRandom(0, 2)],
    authorisedStaus: authorisedStaus[getRandom(0, 1)],
  },
  {
    id: "6",
    MaturityDate: "21-05-2022",
    transactionNo: getRandom(10, 100),
    TransactionsType: type[getRandom(0, 2)],
    status: status[getRandom(0, 2)],
    authorisedStaus: authorisedStaus[getRandom(0, 1)],
  },
  {
    id: "7",
    MaturityDate: "24-05-2022",
    transactionNo: getRandom(10, 100),
    TransactionsType: type[getRandom(0, 2)],
    status: status[getRandom(0, 2)],
    authorisedStaus: authorisedStaus[getRandom(0, 1)],
  },
  {
    id: "8",
    MaturityDate: "17-06-2022",
    transactionNo: getRandom(10, 100),
    TransactionsType: type[getRandom(0, 2)],
    status: status[getRandom(0, 2)],
    authorisedStaus: authorisedStaus[getRandom(0, 1)],
  },
  {
    id: "9",
    MaturityDate: "28-06-2022",
    transactionNo: getRandom(10, 100),
    TransactionsType: type[getRandom(0, 2)],
    status: status[getRandom(0, 2)],
    authorisedStaus: authorisedStaus[getRandom(0, 1)],
  },
  {
    id: "10",
    MaturityDate: "30-07-2022",
    transactionNo: getRandom(10, 100),
    TransactionsType: type[getRandom(0, 2)],
    status: status[getRandom(0, 2)],
    authorisedStaus: authorisedStaus[getRandom(0, 1)],
  },
  {
    id: "11",
    MaturityDate: "07-08-2022",
    transactionNo: getRandom(10, 100),
    TransactionsType: type[getRandom(0, 2)],
    status: status[getRandom(0, 2)],
    authorisedStaus: authorisedStaus[getRandom(0, 1)],
  },
  {
    id: "12",
    MaturityDate: "20-07-2022",
    transactionNo: getRandom(10, 100),
    TransactionsType: type[getRandom(0, 2)],
    status: status[getRandom(0, 2)],
    authorisedStaus: authorisedStaus[getRandom(0, 1)],
  },
  {
    id: "13",
    MaturityDate: "09-08-2022",
    transactionNo: getRandom(10, 100),
    TransactionsType: type[getRandom(0, 2)],
    status: status[getRandom(0, 2)],
    authorisedStaus: authorisedStaus[getRandom(0, 1)],
  },
  {
    id: "14",
    MaturityDate: "13-08-2022",
    transactionNo: getRandom(10, 100),
    TransactionsType: type[getRandom(0, 2)],
    status: status[getRandom(0, 2)],
    authorisedStaus: authorisedStaus[getRandom(0, 1)],
  },
  {
    id: "15",
    MaturityDate: "17-08-2022",
    transactionNo: getRandom(10, 100),
    TransactionsType: type[getRandom(0, 2)],
    status: status[getRandom(0, 2)],
    authorisedStaus: authorisedStaus[getRandom(0, 1)],
  },
  {
    id: "16",
    MaturityDate: "19-09-2022",
    transactionNo: getRandom(10, 100),
    TransactionsType: type[getRandom(0, 2)],
    status: status[getRandom(0, 2)],
    authorisedStaus: authorisedStaus[getRandom(0, 1)],
  },
  {
    id: "17",
    MaturityDate: "05-10-2022",
    transactionNo: getRandom(10, 100),
    TransactionsType: type[getRandom(0, 2)],
    status: status[getRandom(0, 2)],
    authorisedStaus: authorisedStaus[getRandom(0, 1)],
  },
  {
    id: "18",
    MaturityDate: "13-10-2022",
    transactionNo: getRandom(10, 100),
    TransactionsType: type[getRandom(0, 2)],
    status: status[getRandom(0, 2)],
    authorisedStaus: authorisedStaus[getRandom(0, 1)],
  },
  {
    id: "19",
    MaturityDate: "28-10-2022",
    transactionNo: getRandom(10, 100),
    TransactionsType: type[getRandom(0, 2)],
    status: status[getRandom(0, 2)],
    authorisedStaus: authorisedStaus[getRandom(0, 1)],
  },
  {
    id: "20",
    MaturityDate: "06-12-2022",
    transactionNo: getRandom(10, 100),
    TransactionsType: type[getRandom(0, 2)],
    status: status[getRandom(0, 2)],
    authorisedStaus: authorisedStaus[getRandom(0, 1)],
  },
]

export default custodianTransaction